### ISSUE TITLE
How can i modify it and use it in Skim?

### ISSUE THREAD

**Issue by yu-soong** [xrisk/preview-vim#2]
Hi, 

I use skim more offen and want to modify it so that i can use it in skim. simplily replacing "preview" with "skim" won't work since they are in two different folders? can you tell me how to do it? 

thanks!

**Comment by xrisk** [comment]
If you open the Event Viewer in Karabiner and go to “Frontmost application”; you can find the bundle identifier for Skim; simply replace.

**Comment by yu-soong** [comment]
Thank you! it works!

**Comment by xrisk** [comment]
Please note that the nontrivial bindings may not work because the Skim hotkeys for those might be different from the Preview hotkeys. If you decide to edit those yourself, I will gladly accept a PR for a separate Skim version.

**Comment by yu-soong** [comment]
Thanks! I'll let you know when edit it, but now it works just fine ~
